# Site settings
title: DavidBreyer.com
tagline: C# Developer Blog
email: davidbreyer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a professional C# Developer, specializing in building web applications
  using ASP.NET, Web API and Entity Framework.
production_url : http://www.davidbreyer.com
logourl: /assets/images/logo.png # Site logo
author: "David Breyer"
author_thumbnail: "/assets/david_breyer.png" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#80A24D" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: davidbreyer
    twitter: davidbreyer
    facebook: davidbreyer
    linkedin: davidbreyer

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  #Disqus comments manager - shortname
  disqus_shortname: davidbreyer
  
  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-11901677-1
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
